const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILURE = "LOGIN_FAILURE";
const LOGOUT_REQUEST = "LOGOUT_REQUEST";
const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
const LOGOUT_FAILURE = "LOGOUT_FAILURE";
const FB_LOGIN_REQUEST = "FB_LOGIN_REQUEST";
const FB_LOGIN_SUCCESS = "FB_LOGIN_SUCCESS";
const FB_LOGIN_FAILURE = "FB_LOGIN_FAILURE";
const REGISTER_REQUEST = "REGISTER_REQUEST";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_FAILURE = "REGISTER_FAILURE";
const DISABLE_PERMISSIONS = "DISABLE_PERMISSIONS";
const GET_USER_DETAILS_REQUEST = "GET_USER_DETAILS_REQUEST";
const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
const GET_USER_DETAILS_FAILURE = "GET_USER_DETAILS_FAILURE";
const TOGGLE_AUTH_MSG = "TOGGLE_AUTH_MSG";
const REFRESH_TOKEN = "REFRESH_TOKEN";
const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
const VERIFY_CODE_REQUEST = "VERIFY_CODE_REQUEST";
const VERIFY_CODE_SUCCESS = "VERIFY_CODE_SUCCESS";
const VERIFY_CODE_FAILURE = "VERIFY_CODE_FAILURE";
const RESEND_CODE_REQUEST = "RESEND_CODE_REQUEST";
const RESEND_CODE_SUCCESS = "RESEND_CODE_SUCCESS";
const RESEND_CODE_FAILURE = "RESEND_CODE_FAILURE";
const RESET_PASS_REQUEST = "RESET_PASS_REQUEST";
const RESET_PASS_SUCCESS = "RESET_PASS_SUCCESS";
const RESET_PASS_FAILURE = "RESET_PASS_FAILURE";
const SIGN_UP_WITH_PHONE_REQUEST = "SIGN_UP_WITH_PHONE_REQUEST";
const SIGN_UP_WITH_PHONE_SUCCESS = "SIGN_UP_WITH_PHONE_SUCCESS";
const SIGN_UP_WITH_PHONE_FAILURE = "SIGN_UP_WITH_PHONE_FAILURE";
const CHANGE_USER_REACTION_REQUEST = "CHANGE_USER_REACTION_REQUEST";
const CHANGE_USER_REACTION_SUCCESS = "CHANGE_USER_REACTION_SUCCESS";
const CHANGE_USER_REACTION_FAILURE = "CHANGE_USER_REACTION_FAILURE";
const SET_USER_IN_PROGRESS_TEST_REQUEST = "SET_USER_IN_PROGRESS_TEST_REQUEST";
const SET_USER_IN_PROGRESS_TEST_FAILURE = "SET_USER_IN_PROGRESS_TEST_FAILURE";
const SET_USER_IN_PROGRESS_TEST_SUCCESS = "SET_USER_IN_PROGRESS_TEST_SUCCESS";

export const types = {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT_FAILURE,
  LOGOUT_REQUEST,
  LOGOUT_SUCCESS,
  FB_LOGIN_FAILURE,
  FB_LOGIN_REQUEST,
  FB_LOGIN_SUCCESS,
  REGISTER_FAILURE,
  REGISTER_REQUEST,
  REGISTER_SUCCESS,
  DISABLE_PERMISSIONS,
  GET_USER_DETAILS_FAILURE,
  GET_USER_DETAILS_REQUEST,
  GET_USER_DETAILS_SUCCESS,
  TOGGLE_AUTH_MSG,
  VERIFY_CODE_FAILURE,
  VERIFY_CODE_REQUEST,
  VERIFY_CODE_SUCCESS,
  SIGN_UP_WITH_PHONE_FAILURE,
  SIGN_UP_WITH_PHONE_SUCCESS,
  SIGN_UP_WITH_PHONE_REQUEST,
  CHANGE_USER_REACTION_FAILURE,
  CHANGE_USER_REACTION_REQUEST,
  CHANGE_USER_REACTION_SUCCESS,
  RESEND_CODE_FAILURE,
  RESEND_CODE_REQUEST,
  RESEND_CODE_SUCCESS,
  RESET_PASS_FAILURE,
  RESET_PASS_REQUEST,
  RESET_PASS_SUCCESS,
  REFRESH_TOKEN,
  SET_USER_IN_PROGRESS_TEST_REQUEST,
  SET_USER_IN_PROGRESS_TEST_FAILURE,
  SET_USER_IN_PROGRESS_TEST_SUCCESS,
  CHANGE_LANGUAGE,
};
